### ISSUE TITLE
.EXE not responding

### ISSUE THREAD

**Issue by Odin-Kaze** [gameboy9/FF1-PR-Rando#24]
![FF1PRR](https://user-images.githubusercontent.com/119276605/209198629-0c104d5e-4eae-487e-b8f1-438fbc7923b5.png)
I downloaded and extracted the zip and try to open the .exe. what you can see in the attachement is the only result I have.
Press yes just close the window and no do the same.
I installed .net 7.0 and 6.0 and tried again with no luck.
Memoria Is installed and working.

**Comment by Odin-Kaze** [comment]
I have the same error on FF4 Fabul Gauntlet but the Final Fantasy V: Abridged work fine.

**Comment by gameboy9** [comment]
In our next release (hopefully real soon!), we are going to update to .NET 7.0, so hopefully that will resolve this issue.

**Comment by Odin-Kaze** [comment]
The problem what still there but I found a way to make it worked. In the file "FF1 PRR.runtimeconfig.json":
{
  "runtimeOptions": {
    "tfm": "net7.0",
    "framework": {
      "name": "Microsoft.WindowsDesktop.App",
      "version": "7.0.2"
    }
  }
}

the tfm was "net5.0" and the version was "5.0.0". I changed it of the version I have and I was able to open the exe after that.

**Comment by Odin-Kaze** [comment]
Fixed on my side.
